version: '3.8'

services:
  db:
    image: postgres:13.0
    env_file:
      - env/.db
    volumes:
      - postgres_data:/var/lib/postgres/data

  backend:
    build:
      context: ./video_app
      dockerfile: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./video_app:/src/code
    hostname: backend
    ports:
      - 8000:8000
    env_file:
      - env/.backend
    depends_on:
      - db
volumes:
  postgres_data:

